### ISSUE TITLE
Win Installer doesn't work on Win11

### ISSUE THREAD

**Issue by rsmus7** [Uberton/Uberton#19]
the installation windows just doesn't show any clickable button to install it!!!
and the text in the window is not fully visible.

**Comment by Mc-Zen** [comment]
Hi @rsmus7 

I'm really sorry but I must have missed your post!

We've encountered this issue before and it has to do with the display scaling of Windows. Evidently, the GUI of the installer does not know about the scaling factor so that the `Next` button is hidden. 

As a workaround, it is possible to change the scaling to 100% in the Windows settings, run the installer and change the scaling back to the original value. 

Does that help?

**Comment by Mc-Zen** [comment]
We should really write a new installer for Windows from scratch.

**Comment by Mc-Zen** [comment]
It's fixed! We got a new installer that should work fine.
