### ISSUE TITLE
Dispersion relation

### ISSUE THREAD

**Issue by SimonLentner** [Uberton/Uberton#2]
(Presentation Slide 13)

omega= b i + sqrt(k^2c^2-b^2)

**Comment by Mc-Zen** [comment]
Using following wave equation now:
![image](https://user-images.githubusercontent.com/52877387/119272407-f408ae00-bc05-11eb-82c3-6e92d3f8fe38.png)
which leads to a frequency response
![image](https://user-images.githubusercontent.com/52877387/119272426-0b479b80-bc06-11eb-9a74-c22e04d9fcb1.png)
The base frequency can be adapted through changing properties like the size of the resonator, i.e. the length of a string
![image](https://user-images.githubusercontent.com/52877387/119272484-66798e00-bc06-11eb-9724-a19640d5cea4.png)
In this version, the dampening factor has a unit of s⁻¹ instead of m⁻¹ but that allows for better independent control in the plugin.
